version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: md-translation-gpt-app
    volumes:
      - ${SRC_DOC_PATH:-./srcdoc}:/srcdoc:ro
      - ${DST_DOC_PATH:-./dstdoc}:/dstdoc:rw
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_DIR=/dstdoc/.data
    working_dir: /app
    command: "npx md-translation-gpt -p '/srcdoc/**/*' -o /dstdoc -d -a 0.97"
