version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: md-translation-gpt-app
    volumes:
      - ${SRC_DOC_PATH:-./srcdoc}:/srcdoc:ro
      - ${DST_DOC_PATH:-./dstdoc}:/dstdoc:rw
    environment:
      - TZ=Asia/Tokyo
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    working_dir: /app
    command: "npx md-translation-gpt -p '/srcdoc/**/*' -o /dstdoc -v -a 0.97 -d"
