version: '3'

services:
  app:
    volumes:
      - ${SRC_DOC_PATH:-./examples/src}:/srcdoc:ro
      - ${DST_DOC_PATH:-./examples/dst}:/dstdoc:rw
      - .:/app:cached
      - /app/node_modules
    environment:
      # - TS_NODE_IGNORE="false"
      - TS_NODE_FILES="true"
    command: /bin/sh -c "while sleep 1000; do :; done"
