version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/app/Dockerfile
    image: md-translation-gpt-app
    volumes:
      - ..:/app:cached
      - /app/node_modules
    working_dir: /app
    environment:
      # - TS_NODE_IGNORE="false"
      - TS_NODE_FILES="true"
    tty: true
